import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-table1',
  templateUrl: './table1.component.html',
  styleUrls: ['./table1.component.scss']
})
export class Table1Component implements OnInit {

  btcP = [
	{ coin: "Bitcoin", img: "../../../assets/Bitcoin.svg", bs: "Sell", market: "Kraken", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", img: "../../../assets/Bitcoin.svg", bs: "Buy", market: "Bitstamp", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", img: "../../../assets/Bitcoin.svg", bs: "Buy", market: "Coinbase", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", img: "../../../assets/Bitcoin.svg", bs: "Sell", market: "Bitstamp", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", img: "../../../assets/Bitcoin.svg", bs: "Buy", market: "Coinbase", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", img: "../../../assets/Bitcoin.svg", bs: "Sell", market: "Kraken", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", img: "../../../assets/Bitcoin.svg", bs: "Buy", market: "Coinbase", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", img: "../../../assets/Bitcoin.svg", bs: "Buy", market: "Kraken", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", img: "../../../assets/Bitcoin.svg", bs: "Buy", market: "Coinbase", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", img: "../../../assets/Bitcoin.svg", bs: "Buy", market: "Bitfinex", value: (Math.random() * 10000).toFixed(2) },
    { coin: "Bitcoin", img: "../../../assets/Bitcoin.svg", bs: "Buy", market: "Coinbase", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", img: "../../../assets/Bitcoin.svg", bs: "Sell", market: "Kraken", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", img: "../../../assets/Bitcoin.svg", bs: "Buy", market: "Coinbase", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", img: "../../../assets/Bitcoin.svg", bs: "Buy", market: "Bitstamp", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", img: "../../../assets/Bitcoin.svg", bs: "Buy", market: "Bitstamp", value: (Math.random() * 10000).toFixed(2) },
    { coin: "Bitcoin", img: "../../../assets/Bitcoin.svg", bs: "Buy", market: "Coinbase", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", img: "../../../assets/Bitcoin.svg", bs: "Sell", market: "Bitstamp", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", img: "../../../assets/Bitcoin.svg", bs: "Buy", market: "Bitfinex", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", img: "../../../assets/Bitcoin.svg", bs: "Sell", market: "Coinbase", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", img: "../../../assets/Bitcoin.svg", bs: "Buy", market: "Kraken", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", img: "../../../assets/Bitcoin.svg", bs: "Buy", market: "Kraken", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Buy", market: "Kraken", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Sell", market: "Coinbase", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Sell", market: "Kraken", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Sell", market: "Bitfinex", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Sell", market: "Kraken", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Sell", market: "Bitstamp", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Buy", market: "Bitstamp", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Buy", market: "Bitstamp", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Sell", market: "Bitfinex", value: (Math.random() * 10000).toFixed(2) },	
  ]
  
  data1: any[] = [];
  
    ngOnInit() {
      this.data1 = [
	{ coin: "Bitcoin", img: "../../../assets/Bitcoin.svg", bs: "Sell", market: "Coinbase", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Sell", market: "Bitstamp", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Sell", market: "Kraken", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Buy", market: "Bitstamp", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Buy", market: "Coinbase", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Sell", market: "Bitstamp", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Buy", market: "Coinbase", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Sell", market: "Kraken", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Buy", market: "Coinbase", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Buy", market: "Kraken", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Buy", market: "Coinbase", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Buy", market: "Bitfinex", value: (Math.random() * 10000).toFixed(2) },
    { coin: "Bitcoin", bs: "Buy", market: "Coinbase", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Sell", market: "Kraken", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Buy", market: "Coinbase", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Buy", market: "Bitstamp", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Buy", market: "Bitstamp", value: (Math.random() * 10000).toFixed(2) },
    { coin: "Bitcoin", bs: "Buy", market: "Coinbase", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Sell", market: "Bitstamp", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Buy", market: "Bitfinex", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Sell", market: "Coinbase", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Sell", market: "Coinbase", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Sell", market: "Bitstamp", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Sell", market: "Kraken", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Buy", market: "Bitstamp", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Buy", market: "Coinbase", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Sell", market: "Bitstamp", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Buy", market: "Coinbase", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Sell", market: "Kraken", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Buy", market: "Coinbase", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Buy", market: "Kraken", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Buy", market: "Coinbase", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Buy", market: "Bitfinex", value: (Math.random() * 10000).toFixed(2) },
    { coin: "Bitcoin", bs: "Buy", market: "Coinbase", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Sell", market: "Kraken", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Buy", market: "Coinbase", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Buy", market: "Bitstamp", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Buy", market: "Bitstamp", value: (Math.random() * 10000).toFixed(2) },
    { coin: "Bitcoin", bs: "Buy", market: "Coinbase", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Sell", market: "Bitstamp", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Buy", market: "Bitfinex", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Sell", market: "Coinbase", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Sell", market: "Coinbase", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Sell", market: "Bitstamp", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Sell", market: "Kraken", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Buy", market: "Bitstamp", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Buy", market: "Coinbase", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Sell", market: "Bitstamp", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Buy", market: "Coinbase", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Sell", market: "Kraken", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Buy", market: "Coinbase", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Buy", market: "Kraken", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Buy", market: "Coinbase", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Buy", market: "Bitfinex", value: (Math.random() * 10000).toFixed(2) },
    { coin: "Bitcoin", bs: "Buy", market: "Coinbase", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Sell", market: "Kraken", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Buy", market: "Coinbase", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Buy", market: "Bitstamp", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Buy", market: "Bitstamp", value: (Math.random() * 10000).toFixed(2) },
    { coin: "Bitcoin", bs: "Buy", market: "Coinbase", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Sell", market: "Bitstamp", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Buy", market: "Bitfinex", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Sell", market: "Coinbase", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Sell", market: "Coinbase", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Sell", market: "Bitstamp", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Sell", market: "Kraken", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Buy", market: "Bitstamp", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Buy", market: "Coinbase", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Sell", market: "Bitstamp", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Buy", market: "Coinbase", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Sell", market: "Kraken", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Buy", market: "Coinbase", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Buy", market: "Kraken", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Buy", market: "Coinbase", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Buy", market: "Bitfinex", value: (Math.random() * 10000).toFixed(2) },
    { coin: "Bitcoin", bs: "Buy", market: "Coinbase", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Sell", market: "Kraken", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Buy", market: "Coinbase", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Buy", market: "Bitstamp", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Buy", market: "Bitstamp", value: (Math.random() * 10000).toFixed(2) },
    { coin: "Bitcoin", bs: "Buy", market: "Coinbase", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Sell", market: "Bitstamp", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Buy", market: "Bitfinex", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Sell", market: "Coinbase", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Sell", market: "Coinbase", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Sell", market: "Bitstamp", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Sell", market: "Kraken", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Buy", market: "Bitstamp", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Buy", market: "Coinbase", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Sell", market: "Bitstamp", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Buy", market: "Coinbase", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Sell", market: "Kraken", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Buy", market: "Coinbase", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Buy", market: "Kraken", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Buy", market: "Coinbase", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Buy", market: "Bitfinex", value: (Math.random() * 10000).toFixed(2) },
    { coin: "Bitcoin", bs: "Buy", market: "Coinbase", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Sell", market: "Kraken", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Buy", market: "Coinbase", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Buy", market: "Bitstamp", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Buy", market: "Bitstamp", value: (Math.random() * 10000).toFixed(2) },
    { coin: "Bitcoin", bs: "Buy", market: "Coinbase", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Sell", market: "Bitstamp", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Buy", market: "Bitfinex", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Sell", market: "Coinbase", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Sell", market: "Coinbase", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Sell", market: "Bitstamp", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Sell", market: "Kraken", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Buy", market: "Bitstamp", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Buy", market: "Coinbase", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Sell", market: "Bitstamp", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Buy", market: "Coinbase", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Sell", market: "Kraken", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Buy", market: "Coinbase", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Buy", market: "Kraken", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Buy", market: "Coinbase", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Buy", market: "Bitfinex", value: (Math.random() * 10000).toFixed(2) },
    { coin: "Bitcoin", bs: "Buy", market: "Coinbase", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Sell", market: "Kraken", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Buy", market: "Coinbase", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Buy", market: "Bitstamp", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Buy", market: "Bitstamp", value: (Math.random() * 10000).toFixed(2) },
    { coin: "Bitcoin", bs: "Buy", market: "Coinbase", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Sell", market: "Bitstamp", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Buy", market: "Bitfinex", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Sell", market: "Coinbase", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Sell", market: "Coinbase", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Sell", market: "Bitstamp", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Sell", market: "Kraken", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Buy", market: "Bitstamp", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Buy", market: "Coinbase", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Sell", market: "Bitstamp", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Buy", market: "Coinbase", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Sell", market: "Kraken", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Buy", market: "Coinbase", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Buy", market: "Kraken", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Buy", market: "Coinbase", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Buy", market: "Bitfinex", value: (Math.random() * 10000).toFixed(2) },
    { coin: "Bitcoin", bs: "Buy", market: "Coinbase", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Sell", market: "Kraken", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Buy", market: "Coinbase", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Buy", market: "Bitstamp", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Buy", market: "Bitstamp", value: (Math.random() * 10000).toFixed(2) },
    { coin: "Bitcoin", bs: "Buy", market: "Coinbase", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Sell", market: "Bitstamp", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Buy", market: "Bitfinex", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Sell", market: "Coinbase", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Sell", market: "Coinbase", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Sell", market: "Bitstamp", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Sell", market: "Kraken", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Buy", market: "Bitstamp", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Buy", market: "Coinbase", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Sell", market: "Bitstamp", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Buy", market: "Coinbase", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Sell", market: "Kraken", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Buy", market: "Coinbase", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Buy", market: "Kraken", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Buy", market: "Coinbase", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Buy", market: "Bitfinex", value: (Math.random() * 10000).toFixed(2) },
    { coin: "Bitcoin", bs: "Buy", market: "Coinbase", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Sell", market: "Kraken", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Buy", market: "Coinbase", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Buy", market: "Bitstamp", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Buy", market: "Bitstamp", value: (Math.random() * 10000).toFixed(2) },
    { coin: "Bitcoin", bs: "Buy", market: "Coinbase", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Sell", market: "Bitstamp", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Buy", market: "Bitfinex", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Sell", market: "Coinbase", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Sell", market: "Coinbase", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Sell", market: "Bitstamp", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Sell", market: "Kraken", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Buy", market: "Bitstamp", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Buy", market: "Coinbase", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Sell", market: "Bitstamp", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Buy", market: "Coinbase", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Sell", market: "Kraken", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Buy", market: "Coinbase", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Buy", market: "Kraken", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Buy", market: "Coinbase", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Buy", market: "Bitfinex", value: (Math.random() * 10000).toFixed(2) },
    { coin: "Bitcoin", bs: "Buy", market: "Coinbase", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Sell", market: "Kraken", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Buy", market: "Coinbase", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Buy", market: "Bitstamp", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Buy", market: "Bitstamp", value: (Math.random() * 10000).toFixed(2) },
    { coin: "Bitcoin", bs: "Buy", market: "Coinbase", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Sell", market: "Bitstamp", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Buy", market: "Bitfinex", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Sell", market: "Coinbase", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", img: "../../../assets/Bitcoin.svg", bs: "Sell", market: "Coinbase", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Sell", market: "Bitstamp", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Sell", market: "Kraken", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Buy", market: "Bitstamp", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Buy", market: "Coinbase", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Sell", market: "Bitstamp", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Buy", market: "Coinbase", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Sell", market: "Kraken", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Buy", market: "Coinbase", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Buy", market: "Kraken", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Buy", market: "Coinbase", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Buy", market: "Bitfinex", value: (Math.random() * 10000).toFixed(2) },
    { coin: "Bitcoin", bs: "Buy", market: "Coinbase", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Sell", market: "Kraken", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Buy", market: "Coinbase", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Buy", market: "Bitstamp", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Buy", market: "Bitstamp", value: (Math.random() * 10000).toFixed(2) },
    { coin: "Bitcoin", bs: "Buy", market: "Coinbase", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Sell", market: "Bitstamp", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Buy", market: "Bitfinex", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Sell", market: "Coinbase", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Sell", market: "Coinbase", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Sell", market: "Bitstamp", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Sell", market: "Kraken", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Buy", market: "Bitstamp", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Buy", market: "Coinbase", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Sell", market: "Bitstamp", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Buy", market: "Coinbase", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Sell", market: "Kraken", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Buy", market: "Coinbase", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Buy", market: "Kraken", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Buy", market: "Coinbase", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Buy", market: "Bitfinex", value: (Math.random() * 10000).toFixed(2) },
    { coin: "Bitcoin", bs: "Buy", market: "Coinbase", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Sell", market: "Kraken", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Buy", market: "Coinbase", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Buy", market: "Bitstamp", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Buy", market: "Bitstamp", value: (Math.random() * 10000).toFixed(2) },
    { coin: "Bitcoin", bs: "Buy", market: "Coinbase", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Sell", market: "Bitstamp", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Buy", market: "Bitfinex", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Sell", market: "Coinbase", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Sell", market: "Coinbase", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Sell", market: "Bitstamp", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Sell", market: "Kraken", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Buy", market: "Bitstamp", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Buy", market: "Coinbase", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Sell", market: "Bitstamp", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Buy", market: "Coinbase", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Sell", market: "Kraken", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Buy", market: "Coinbase", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Buy", market: "Kraken", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Buy", market: "Coinbase", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Buy", market: "Bitfinex", value: (Math.random() * 10000).toFixed(2) },
    { coin: "Bitcoin", bs: "Buy", market: "Coinbase", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Sell", market: "Kraken", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Buy", market: "Coinbase", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Buy", market: "Bitstamp", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Buy", market: "Bitstamp", value: (Math.random() * 10000).toFixed(2) },
    { coin: "Bitcoin", bs: "Buy", market: "Coinbase", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Sell", market: "Bitstamp", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Buy", market: "Bitfinex", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Sell", market: "Coinbase", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Sell", market: "Coinbase", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Sell", market: "Bitstamp", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Sell", market: "Kraken", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Buy", market: "Bitstamp", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Buy", market: "Coinbase", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Sell", market: "Bitstamp", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Buy", market: "Coinbase", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Sell", market: "Kraken", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Buy", market: "Coinbase", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Buy", market: "Kraken", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Buy", market: "Coinbase", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Buy", market: "Bitfinex", value: (Math.random() * 10000).toFixed(2) },
    { coin: "Bitcoin", bs: "Buy", market: "Coinbase", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Sell", market: "Kraken", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Buy", market: "Coinbase", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Buy", market: "Bitstamp", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Buy", market: "Bitstamp", value: (Math.random() * 10000).toFixed(2) },
    { coin: "Bitcoin", bs: "Buy", market: "Coinbase", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Sell", market: "Bitstamp", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Buy", market: "Bitfinex", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Sell", market: "Coinbase", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Sell", market: "Coinbase", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Sell", market: "Bitstamp", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Sell", market: "Kraken", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Buy", market: "Bitstamp", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Buy", market: "Coinbase", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Sell", market: "Bitstamp", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Buy", market: "Coinbase", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Sell", market: "Kraken", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Buy", market: "Coinbase", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Buy", market: "Kraken", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Buy", market: "Coinbase", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Buy", market: "Bitfinex", value: (Math.random() * 10000).toFixed(2) },
    { coin: "Bitcoin", bs: "Buy", market: "Coinbase", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Sell", market: "Kraken", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Buy", market: "Coinbase", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Buy", market: "Bitstamp", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Buy", market: "Bitstamp", value: (Math.random() * 10000).toFixed(2) },
    { coin: "Bitcoin", bs: "Buy", market: "Coinbase", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Sell", market: "Bitstamp", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Buy", market: "Bitfinex", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Sell", market: "Coinbase", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Sell", market: "Coinbase", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Sell", market: "Bitstamp", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Sell", market: "Kraken", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Buy", market: "Bitstamp", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Buy", market: "Coinbase", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Sell", market: "Bitstamp", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Buy", market: "Coinbase", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Sell", market: "Kraken", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Buy", market: "Coinbase", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Buy", market: "Kraken", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Buy", market: "Coinbase", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Buy", market: "Bitfinex", value: (Math.random() * 10000).toFixed(2) },
    { coin: "Bitcoin", bs: "Buy", market: "Coinbase", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Sell", market: "Kraken", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Buy", market: "Coinbase", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Buy", market: "Bitstamp", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Buy", market: "Bitstamp", value: (Math.random() * 10000).toFixed(2) },
    { coin: "Bitcoin", bs: "Buy", market: "Coinbase", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Sell", market: "Bitstamp", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Buy", market: "Bitfinex", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Sell", market: "Coinbase", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Sell", market: "Coinbase", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Sell", market: "Bitstamp", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Sell", market: "Kraken", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Buy", market: "Bitstamp", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Buy", market: "Coinbase", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Sell", market: "Bitstamp", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Buy", market: "Coinbase", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Sell", market: "Kraken", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Buy", market: "Coinbase", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Buy", market: "Kraken", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Buy", market: "Coinbase", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Buy", market: "Bitfinex", value: (Math.random() * 10000).toFixed(2) },
    { coin: "Bitcoin", bs: "Buy", market: "Coinbase", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Sell", market: "Kraken", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Buy", market: "Coinbase", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Buy", market: "Bitstamp", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Buy", market: "Bitstamp", value: (Math.random() * 10000).toFixed(2) },
    { coin: "Bitcoin", bs: "Buy", market: "Coinbase", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Sell", market: "Bitstamp", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Buy", market: "Bitfinex", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Sell", market: "Coinbase", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Sell", market: "Coinbase", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Sell", market: "Bitstamp", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Sell", market: "Kraken", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Buy", market: "Bitstamp", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Buy", market: "Coinbase", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Sell", market: "Bitstamp", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Buy", market: "Coinbase", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Sell", market: "Kraken", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Buy", market: "Coinbase", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Buy", market: "Kraken", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Buy", market: "Coinbase", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Buy", market: "Bitfinex", value: (Math.random() * 10000).toFixed(2) },
    { coin: "Bitcoin", bs: "Buy", market: "Coinbase", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Sell", market: "Kraken", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Buy", market: "Coinbase", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Buy", market: "Bitstamp", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Buy", market: "Bitstamp", value: (Math.random() * 10000).toFixed(2) },
    { coin: "Bitcoin", bs: "Buy", market: "Coinbase", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Sell", market: "Bitstamp", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Buy", market: "Bitfinex", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Sell", market: "Coinbase", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Sell", market: "Coinbase", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Sell", market: "Bitstamp", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Sell", market: "Kraken", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Buy", market: "Bitstamp", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Buy", market: "Coinbase", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Sell", market: "Bitstamp", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Buy", market: "Coinbase", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Sell", market: "Kraken", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Buy", market: "Coinbase", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Buy", market: "Kraken", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Buy", market: "Coinbase", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Buy", market: "Bitfinex", value: (Math.random() * 10000).toFixed(2) },
    { coin: "Bitcoin", bs: "Buy", market: "Coinbase", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Sell", market: "Kraken", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Buy", market: "Coinbase", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Buy", market: "Bitstamp", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Buy", market: "Bitstamp", value: (Math.random() * 10000).toFixed(2) },
    { coin: "Bitcoin", bs: "Buy", market: "Coinbase", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Sell", market: "Bitstamp", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Buy", market: "Bitfinex", value: (Math.random() * 10000).toFixed(2) },
	{ coin: "Bitcoin", bs: "Sell", market: "Coinbase", value: (Math.random() * 10000).toFixed(2) },
	  ];
    //   this.setOption(this.data1);
    //   setInterval(() => {      
  	//   this.data1 = this.randomData(1000, this.data1, false, 1);
    //   }, 200);
    }

    randomData(x, data: any[], isNew: boolean, val: number): any[] {
      for (let i = 0; i < val; i++) {
        isNew ? '' : data.shift();
        data.push((Math.random() * x + 100 * (Math.round(Math.random()) * 2 - 1
  ) + 7800).toFixed(2));
      }
      return data;
    }      

    change(e) {
  	this.data1 = this.randomData(1000, [], true, 12);
    }
  
  constructor() { }
setOption(data1) {}

}
